name: Nix

concurrency:
  group: nix-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: |
          nix flake check

      - name: Build Cli (Default)
        run: |
          nix build

      - name: Build Gui
        run: |
          nix build .#wrapped-fit2srt-gui
