name: Nix

concurrency:
  group: nix-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: check
        run: |
          nix flake check
